### ISSUE TITLE
API - A001 번개장터 - 김유진

### ISSUE THREAD

**Issue by dearyeon** [Konkuk-JJabaries/Product#12]
- [x] list 포맷
- [x] list detail 포맷
- [x] 디테일 잡기 ex) date 
- [x] site_code 001 인지... type으로 해야하는지.. ?
- [ ] list detail의 pid불러오기

**Comment by IMRaccoon** [comment]
date 는 YYYY-MM-DD 형식으로 만들어주세요~
ex) 2020-01-01

**Comment by IMRaccoon** [comment]
site_code는 001입니다 interface 에 지정이 되어있어요~

site_code 마우스 갖다대거나 ctrl + 클릭 해보면 설명이 제대로 나올꺼에요
