### ISSUE TITLE
API - A005 헬로마켓 - 류수진

### ISSUE THREAD

**Issue by dearyeon** [Konkuk-JJabaries/Product#16]
- [x]  기본 설정
- [x]  product list의 response interface 구현
- [x]  product detail의 response detail 구현
- [x]  check connection 기능
- [x]  키워드에 따른 product list 요청하고 받아오기
- [x]  아이디에 따른 product detail 요청하고 받아오기
- [ ]  date 가져올 때 분 단위를 년-월-일 형식으로 변환하기

**Comment by suzn2** [comment]
- [ ] ㅇㅇ

- [ ] ㅇㅇ

**Comment by ryusuz** [comment]
시간이 3분전 이렇게 나오는데 날짜로 어떻게 변환시키나요
