### ISSUE TITLE
Code Deployment 작업

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/Product#19]
# 1. 개요
수동으로 작업해야할 요소들을 Circle CI를 이용하여 자동화

# 2. 주요 사항
- [x] CI Test 제외 (-> No Test로 실시)
- [x] 자동으로 Build 되는지 테스트
- [ ] 자동으로 폴더 구조를 변경할 수 있는지 확인

**Comment by s5kywa1k3r** [comment]
과정
1. 프로젝트 폴더에 .circleci 폴더를 만듬
2. .circleci 폴더에 config.yml을 만듬

실행과정
1. ssh로 명령어를 보냄 지금같은 경우는 "Script 실행" 명령어를 보냄
2. 스크립트에 deploy하는 명령어들을 수행

**Comment by IMRaccoon** [comment]
Circle CI 가 CD의 역할을 제대로 해준다면 CI 도 스크립트화해서 문제없이 할 수 있기 때문에

잘 진행해주시고 전달해주세요 ^^ 👍

**Comment by s5kywa1k3r** [comment]
현재 s5kywa1k3r/Product master branch에 merge가 발생할 경우 자동으로 실행하도록 설정해 놓았으나 다른 branch에 push 되어도 같이 실행되는 게 확인됨.

**Comment by s5kywa1k3r** [comment]
circle-CI 위 해결책으로는 모든 branch에 .circleci 폴더를 넣어서 동일한 기능을 수행하도록 하면 해결이됨

**Comment by s5kywa1k3r** [comment]
circle-CI에서 github action으로 변경을 시도중

**Comment by s5kywa1k3r** [comment]
CI를 github action으로 적용하였으나 Secret 기능은 forked -> upstream으로 PR할 경우 사용이 불가함.
