### ISSUE TITLE
CI/CD 관련 각 팀 요청사항

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/Product#38]
# CI/CD 관련 각 팀 요청사항

## 개요
Github Action으로 CI/CD를 구축하였으나 현재 Github Action 자체의 보안 차원의 조치로 인하여 자동 배포를 이용하기 위해선 아래의 작업을 거쳐야 함.
이에 따라 이 요청 사항을 전 팀원 모두에게 공지하기 위해 본 Issue를 작성함.

## 문제점
1. github action으로 자동 배포를 함.
2. 자동 배포는 SSH 연결로 명령어를 수행하는 식으로 배포
3. SSH로 서버에 접속하기 위해선 Key 값이 담긴 파일이 필요
4. Repository에 Key 값을 저장하는 것은 보안에 있어 상당한 문제를 야기함
5. Github에는 값을 암호화 하여 저장해 주는 Secret이라는 기능이 있음.
6. Forked Repository에서 Upstream Repository로 Pull Request 할 경우 Secret 기능을 사용할 수 없음. 따라서 위의 2번 Action이 불가

## 요청사항
1. Forked Repository에서 Upstream Repository에 PR을 할 경우 Upstream Repository에 각 Team Repository (ex. front, back) 이름으로 branch를 생성하여 생성된 branch에 PR
2. PR을 승인하고 생성된 branch에서 master branch로 PR 요청.

구조: Forked/ex_branch -> [PR] -> Upstream/ex_branch -> [PR] -> Upstream/master

### 위의 순서를 지켜서 Upstream으로 PR을 하기를 요청.

**Comment by IMRaccoon** [comment]
넵

**Comment by Biccon** [comment]
복잡쓰

**Comment by s5kywa1k3r** [comment]
복잡하지만 우리 repo 구조가 branch로 작업하는게 아니라 fork로 작업해서 어쩔수 없습니다... ㅜㅜ
나중에 더 하면 bot 설정해서 하겠는데 그게 더 복잡해서 포기합니다.
