### ISSUE TITLE
프론트에서 생각하는 개선점

### ISSUE THREAD

**Issue by Biccon** [Konkuk-JJabaries/Product#4]
1. category를 어떻게 사용 할 것인가?
- 11번가, 셀잇 등 카테고리가 있는 서비스가 있음. 혹은 당근마켓 등 카테고리 분류가 없는 서비스가 있음
- 검색 결과를 DB에 저장하는 구조로 한다고 하였고, DB Table에 카테고리 분류를 함께 저장하고 있음
- 카테고리 분류가 있는 사이트와 없는 사이트에서 각각 크롤링 카테고리 정보가 달라지는데 이에 대한 처리는?
- 중고 검색 UX적 관점에서, 사용자가 자신이 필요로 하는 '물건'을 검색하는 경우가 많은지, 혹은 카테고리별로 검색하는 경우가 많은지?
- 둘 다 염두하고 사이트별로 다른 기준을 적용한다고 하면 통일성을 해치는 결과가 나오지 않을지?
>  프론트 입장에서는 category가 있어야 하는 당위성이 조금 떨어진다고 생각

2. frontend측 에서 요구하는 RESTAPI Design
- 고려하고 있는 layout에서, 처음 검색하는 시점에서 각 사이트별 검색 결과를 보여주고, 사이트별 페이징을 생각함
  이유는, 여러개의 사이트에서 검색하고 정보를 불러올 때, 사이트별 item들을 순서대로 모아서 보여줘야 하는지? 섞어서 보여줘야 하는지? 를 생각해 보았을 때 사이트별로 나눠서 보여주는 것이 낫다고 생각함
- 따라서, 전체 검색 결과가 나오는 api와, 사이트별 페이징 결과가 나오는 api가 (내부적으로) 분리 되었으면 좋겠다고 생각함.   (query string 또는 body에 따라서 siteId가 있으면 해당 사이트에서만 불러오는 형태 등으로)

3. detail response interface에서 받아야 할 data form
 - SellerID는 사이트마다 아이디가 다르므로, 굳이 보여줄 필요가 없다고 생각하여 제외 필요
 - Location, FreeShip에 대한 optional한 data 추가 필요

**Comment by IMRaccoon** [comment]
1. category 의 도입에 대한 이유
 - 기본적인 Layout을 사이트별 특징을 뽑아 오마주 할 것이라는 판단하에 필요성을 느껴 만듦
 - 5개의 중고 판매 관련 사이트를 확인해보고 경험해본 결과 category가 훨씬 더 편함을 느꼈음
 - category가 없는 사이트의 경우에 사용할 방법은 다음과 같음
    1. DB를 24시간 주기로 Update할 예정이었음
    2. category가 있는 경우 category에 있는 정보들을 가져오는 것을 목표로
    3. category가 없는 경우 category 명 (ex. 마우스 등) 을 검색한 결과를 토대로 가져올 생각
    4. 이에대한 정확성 판단은 (다른 걸 파는데 가져온 건 아닌 지? 등) 서버쪽에서 해결을 할 생각이었음
    5. 그리고 이에 따라 Category 명을 조금씩 바꾸는 것을 고려하면서 셀잇에서 따온 카테고리 명 이었음
 - 당연히 어떤 사이트는 카테고리가 있고, 어떤 사이트는 없고 하면 안되기 때문에 위의 방식대로 운용하는 것을 생각하고 있었음
 - Layout이 사이트별로 분류될 거라는 생각을 못했기 때문.

2. 반영할 만한 내용임.
 - 사이트별로 분류된 결과물 그리고 전체 결과물을 분류하는 내용에 대한 API Design에 대한 것은 찬성
 - 관련 요청에 대한 interface 수정 요망, 
 - 어느정도 정리된 이후 관련된 내용까지 모두 고려하여 DB 구현하겠음

3. 피드백 주기적으로 요청 요망
 - 필요없는 필드가 SellerID만 지워주면 되는지?? 
 - 그게 아니라면 어느정도 정해진 form을 보고 확인한다음 반영하는 게 나을 듯 함.
 - 좀 더 얘기해봐야겠지만, 사이트별 optional한 정보는 최소한으로 했으면 함,
 - 사이트 별로 보여주는 내용이 많이 달라지면 공통적인 색이 떨어지기 때문
 - optional 한 데이터는 API팀에서 개발하면서 front쪽으로 인수인계하도록 API팀에게 전달할 예정
 - optional 데이터를 넣기 위한 etc : object 라는 response field 필요 인지

**Comment by beoms96** [comment]
2. 이 레이아웃이 어떻게 구성되느냐에 따라서 DB의 구조가 좀 바뀔 것 같은데, 사용자 입장에서 사이트 별로 나눠서 보여주는 거면 굳이 이 사이트를 쓸 이유가 없지 않을까라는 생각이 전부터 계속 들었습니다 . 그래서 가격기준이라던가 기준을 둬서 그 기준에 제일 부합하는 것부터 차례대로 섞어서 보여주는 것이 어떤지에 대해 여쭙고 싶습니다!

**Comment by wjp103** [comment]
@bm1478 
2. 현재 api 를 받아서 보여주는 부분의 Layout 을 프로토타입을 작성해서 슬랙에 이미지 파일로 공유를 했습니다 .물론 가격대 별로 보여주는 것은 모든 쇼핑몰에서 가지고 있는 기능이며, 또한 그 기능 또한 추가적으로 진행할 것이라고 생각합니다. 
근데 우리는 쇼핑몰이 아니라 8개의 사이트에서 가져온 데이터를 보여주는 사이트를 만드는게 아닌가 생각합니다.
차례대로 섞어서 보여준다면 모든 api 를 request한 이후에 데이터를 받아오고 다시 정렬하고 다시 보여줘야하는 방식으로 해야하는 데, 이 점 또한 문제라고 생각합니다.
개인적으로 게시판의 경우 작성된 시간 순서대로 보여주는 것이 원칙이 맞다고 생각하고. 사이트 별로 정리를 해주는 화면 구성이 검색 결과 페이지에 제일 우선으로 보여 주어야 한다고 생각합니다. 기타 추가적으로 가격 순서대로 정리하는 페이지의 경우는 부가적인 기능이라고 생각합니다.

**Comment by wjp103** [comment]
@IMRaccoon 
1. 카테고리의 사용 용도는 중고사이트에서 사실 크게 의미 없다고 생각을 전제로 하여 Layout 을 구성하다보니 사이트별로 정리하여 보여주는게 더 사용자 입장에서 편리하다고 생각하였음. 
 카테고리 컴포넌트를 추가해서 그 결과를 보여주는 화면 또한 충분히 지금 나온 프로토타입에서 보여줄수있음. 
 카테고리 별로 상품들을 보여주는 페이지가 필요할지에 대한 논의가 충분히 진행이 되면 좋을거같음

**Comment by IMRaccoon** [comment]
-  사이트별로 나누는 것이 훨씬 더 가독성이 좋겠지만, 
- 만약 사이트가 10개로 증설된다면?? 거기에 대한 고려도 필요할 것 같음.
- 이러한 이유로 카테고리의 필요성을 느꼈고, UX적 관점을 좀더 판단해야될 것 같음.
- 확실히 사이트별로 분리되는 것이 눈에 더 잘 들어오지만, 
- 단순히 모델명을 구입하는 것, 뿐만 아니라 일반 쇼핑몰을 들어와서 둘러보는 데에는 카테고리 같은 분류도 필요할 것으로 판단했음 피드백 바람

@wjp103 @Biccon

**Comment by wjp103** [comment]
@IMRaccoon 

- 그래서 우리가 올린 프로토타입을 보면 일반적인 쇼핑몰 상품들에 대한 카테고리가 아닌 사이트별 카테고리로 만듬.
- 중고 상품의 경우 키워드 기반 물품을 찾는경우가 더 빈번하다고 생각했음.
- 그 이후에 해당 사이트에서 더 궁금한 내용이 있으면 더보기 버튼이 존재하여 상품들을 무한스크롤링으로 보여줄거임.
- 즉 사이트를 통합하는 페이지는 아직은 고려하지 않았고 사이트 별로 정리하는게 맞다고 판단하여서 진행하였음.

**Comment by IMRaccoon** [comment]
@wjp103  @Biccon 

### 두 가지 컨셉 제안
1. 페이지별 출력
    - 페이지 별로 등록순 출력을 해주며
    - 해당 영역에서 검색을 했을 시 사이트 별로 나뉘어진 상태를 보여준다.
2. 전체 출력
    - 페이지 별 분리를 하지 않고, 등록순, 또는 자체 정책을 정한 순서대로 출력한다.
    - 사실 정형화된 사이트가 아니다보니 가격순으로 보여주기는 힘듦.
    - 이 사이트에서는 카테고리를 활용해 출력한다.
<br>
어떻게 생각하는 지?

**Comment by wjp103** [comment]
@IMRaccoon 
- 맞음. 우리 팀끼리 의논한게 그렇게 진행하려고 했음. 
- 다만 접근성이 편한방향이 어느쪽이 나을진 모르겠어서 일단 두페이지 모두 제작하고 그 이후에 편의성이 가장 좋은 방향으로 진행하려고함.
