### ISSUE TITLE
추가 논의대상 (db, frontend team 방향성)

### ISSUE THREAD

**Issue by Biccon** [Konkuk-JJabaries/Product#5]
1. DB 구조 사용의 필요성에 대한 근본적인 의문 제기
- 기존에 했던 얘기인데, 조금씩 그림이 그려짐에 따라 의문을 다시 제기합니다. 
- 현재 aws free tier 서버임에도 불구, 2개 사이트 까지는 큰 속도저하 없이 검색되는 결과를 보이는데 최종 8개 사이트를 각 각 크롤링 함에 있어서 DB의 필요성 자체를 재고해볼 필요가 있다고 느낌
- 처음 생각은 DB에 저장을 기본으로 했지만 refresh 문제나, DB에 있지만 추가적으로 크롤링 되지 않은 정보를 다시 크롤링 하겠다는 정책이 현재 없는 상황
- 따라서 비교 확인 해보고 큰 성능의 저하가 없으면 요청시 바로 raw data를 formalization 해서 반환 하는것이 어떤지 의문 제기

2. 프론트 팀 진전도 및 추후 팀 방향성 논의 필요성 제기
- 프론트 팀 내에서 1월 12일 전체적인 layout 구성에 대한 회의를 진행하였고, prototype 까지 구성해 보았음
- 월,수 팀내 스터디를 진행하고 있는데 추가적으로 구성한 layout에 대해 동시다발적인 개발 진행을 시작하자고 얘기 나왔고 곧바로 착수할 예정
- 프론트 팀 내부적으로 구현이 서둘러서 마무리가 되면 유지보수적인 측면에서는 프론트 팀을 유지하되, 외적인 측면에서는 팀 운용을 어떻게 하면 좋을지?
- 방관하는 것보다 다른 팀에 도움이 되는 방향이 좋을것 같다고 생각하는데, 추후 논의 대상이 되어야 할 것 같음

**Comment by s5kywa1k3r** [comment]
1. DB 구조에 관련하여선 현 시점에서는 Server 팀에서는 DB를 사용하는 형태로 서버를 구축할 것입니다.
하지만 본 issue가 close 된 후의 결과에 따라 DB를 사용하지 않을 수도 있음을 인지하고 있겠습니다.

**Comment by IMRaccoon** [comment]
1. DB 사용에 대한 이점은 충분이 있음을 먼저 밝히고 시작하겠음
 - 현재 서버가 낮은 단계에 머무름에도 2개의 사이트 속도 문제는 없는 것 확인했음
 - 하지만, 대략 10개로 예상하고 있는 목표 사이트의 API 속도에 대해서는 장담할 수 없음
 - 또한, 해당 서버들이 항상 문제 없이 돌아갈꺼라는 판단을 버려야 함.
 - 게다가 Client 의 숫자, 우리 서버에 접속하는 인원들이 적기 때문에 수월하게 할 수 있음,
 - 효율적으로 할 방법을 찾아야겠지만, 사이트가 늘어나고 모든 request에 하나하나 API를 써주기에는 리스크가 큼

2. 프론트 팀의 진전도가 아직 눈에 보이는 결과물이 없기 때문에 섣불리 판단하기 이름
 - 레이아웃이 나왔지만 그렇게 결과물이 1월말까지 나올 수 있을 지는 제대로 시작하지 않은 상황에서는 판단이 이름
 - 프론트 팀쪽에서 필요로 한 form 과 API 쪽에서 뽑아낼 수 있는 form의 싱크로를 맞출 시간이 필요하다고 생각함
 - 문제 없이 잘된다는 전제하에 이후 진행할 일은 차후 논의해 봐야함.

**Comment by beoms96** [comment]
1. 현 상황에서 Database시스템을 AWS의 RDS를 쓸 것 같은데 10개정도 되는 사이트의 데이터를 RDS에 저장해놓은뒤 불러오는 시간과, api로 바로 formailzation 해서 불러오는 시간을 비교한 뒤에 판단하면 될 것 같습니다.

**Comment by beoms96** [comment]
1. 현재 사이트에서 동일한 형식의 폼으로 추출하는 과정이 진행이 안 되어 있어서 일단 사이트 한개에서 데이터를 뽑아서 저장해놓고 검색어 요청이 들어오면 DB에서 확인 후 있으면 반환, 없으면 api 호출 데이터 보여줌까지는 코드를 짜놓은 상태입니다.

**Comment by IMRaccoon** [comment]
Database도 결국 서버간의 통신이기 때문에 Delay는 충분히 걸릴 수 있습니다.

일단 DB를 유지하고, API 팀쪽 사이트 5개가 개발된 다음 속도 비교를 한 뒤에 판단해도 될 것 같습니다.

현재 팀 내에 인력이 부족하지 않기 때문에 DB는 일단 구축합시다.

**Comment by IMRaccoon** [comment]
본 이슈에 대한 내용 확인해주세요 확인하고 문제없으면 마지막 코맨트에 reaction 달아주세요
